### ISSUE TITLE
Error While Generating Path

### ISSUE THREAD

**Issue by GaganBhat** [Endoman123/motion-profile-generator#2]
So I tried to make an extremely simple path. And instantly got errors in my console. 
Here are the screenshots. I believe it's related to something regarding the measurements.
![image](https://user-images.githubusercontent.com/25236969/36993940-2bb7e260-2075-11e8-912a-6d6e74aaed41.png)

Here are the points I am using.

![image](https://user-images.githubusercontent.com/25236969/36993963-3b1e6ca6-2075-11e8-8e13-216147f0c53e.png)

**Comment by Endoman123** [comment]
Tested the waypoints on my own copy, worked just fine. Can you send me the entire console printout? 

The main thing I'm looking for is something that says "Caused by ___________;" JavaFX applications that throw exceptions always throw the InvocationTargetException first, I need the cause of it.

**Comment by GaganBhat** [comment]
Here is the complete log. 
https://hastebin.com/qoyefesoto.tex

**Comment by GaganBhat** [comment]
![image](https://user-images.githubusercontent.com/25236969/37069513-51056178-2179-11e8-8cf2-dfc105e879a3.png)

Alright, so I did `./gradlew jar` and it ran the jar it built. And it worked just fine. But when I run it by doing `./gradlew run`, it crashes every time. Weird xD.

**Comment by Endoman123** [comment]
Strange, in the crash logs it seems that it can't find the proper natives for your platform. Are you using windows x64 or x86?

**Comment by Endoman123** [comment]
You might have some leftover installations of your JDK if the :jar task works fine, but the :run task doesn't. Check to make sure you are using the 64-bit JDK and not the 32-bit JDK to build and run your stuff.

**Comment by Endoman123** [comment]
Issue closed. Will reopen if problem persists.
